apiVersion: v1
kind: Service
metadata:
  name: readstack-nz-service
  labels:
    app: readstack-nz
spec:
  type: LoadBalancer
  ports:
      - port: 6121
        targetPort: 6121
  selector:
    app: readstack-nz
