apiVersion: v1
kind: Service
metadata:
  name: writemem-service
  labels:
    app: writemem
spec:
  type: LoadBalancer
  ports:
      - port: 6118
        targetPort: 6118
  selector:
    app: writemem
