apiVersion: v1
kind: Service
metadata:
  name: writemem-service
  labels:
    app: writemem
spec:
  type: LoadBalancer
  ports:
      - port: 5252
        targetPort: 5252
  selector:
    app: writemem
