apiVersion: v1
kind: Service
metadata:
  name: readfile-nz-service
  labels:
    app: readfile-nz
spec:
  type: LoadBalancer
  ports:
      - port: 6125
        targetPort: 6125
  selector:
    app: readfile-nz
