apiVersion: v1
kind: Service
metadata:
  name: hashecute-service
  labels:
    app: hashecute
spec:
  type: LoadBalancer
  ports:
      - port: 6126
        targetPort: 6126
  selector:
    app: hashecute
