apiVersion: v1
kind: Service
metadata:
  name: seteax-nz-service
  labels:
    app: seteax-nz
spec:
  type: LoadBalancer
  ports:
      - port: 6115
        targetPort: 6115
  selector:
    app: seteax-nz
