apiVersion: v1
kind: Service
metadata:
  name: writemem-nz-service
  labels:
    app: writemem-nz
spec:
  type: LoadBalancer
  ports:
      - port: 5252
        targetPort: 5252
  selector:
    app: writemem-nz
