apiVersion: v1
kind: Service
metadata:
  name: writestack-service
  labels:
    app: writestack
spec:
  type: LoadBalancer
  ports:
      - port: 5252
        targetPort: 5252
  selector:
    app: writestack
