apiVersion: v1
kind: Service
metadata:
  name: writestack-service
  labels:
    app: writestack
spec:
  type: LoadBalancer
  ports:
      - port: 6122
        targetPort: 6122
  selector:
    app: writestack
