apiVersion: v1
kind: Service
metadata:
  name: writestack-nz-service
  labels:
    app: writestack-nz
spec:
  type: LoadBalancer
  ports:
      - port: 6123
        targetPort: 6123
  selector:
    app: writestack-nz
