apiVersion: v1
kind: Service
metadata:
  name: readstack-service
  labels:
    app: readstack
spec:
  type: LoadBalancer
  ports:
      - port: 5252
        targetPort: 5252
  selector:
    app: readstack
