apiVersion: v1
kind: Service
metadata:
  name: readstack-service
  labels:
    app: readstack
spec:
  type: LoadBalancer
  ports:
      - port: 6120
        targetPort: 6120
  selector:
    app: readstack
