apiVersion: v1
kind: Service
metadata:
  name: dontcrash-service
  labels:
    app: dontcrash
spec:
  type: LoadBalancer
  ports:
      - port: 5252
        targetPort: 5252
  selector:
    app: dontcrash
