apiVersion: v1
kind: Service
metadata:
  name: dontcrash-service
  labels:
    app: dontcrash
spec:
  type: LoadBalancer
  ports:
      - port: 6113
        targetPort: 6113
  selector:
    app: dontcrash
