apiVersion: v1
kind: Service
metadata:
  name: readmem-nz-service
  labels:
    app: readmem-nz
spec:
  type: LoadBalancer
  ports:
      - port: 5252
        targetPort: 5252
  selector:
    app: readmem-nz
