apiVersion: v1
kind: Service
metadata:
  name: readmem-nz-service
  labels:
    app: readmem-nz
spec:
  type: LoadBalancer
  ports:
      - port: 6117
        targetPort: 6117
  selector:
    app: readmem-nz
