apiVersion: v1
kind: Service
metadata:
  name: readfile-service
  labels:
    app: readfile
spec:
  type: LoadBalancer
  ports:
      - port: 6124
        targetPort: 6124
  selector:
    app: readfile
